### ISSUE TITLE
Add a License and CoC

### ISSUE THREAD

**Issue by erikdstock** [nedredmond/dsa-ui#46]
I'd propose we decide on something in the comments of this issue to start. Off the top of my head I'd say we start with sensible default like MIT & the Contributors Covenant, but maybe we should look for something non-commercial as well?

**Comment by nedredmond** [comment]
I've been looking at licenses for a while now and my head is swimming.

- [Software can't be open source while restricting how it is used](https://opensource.org/osd-annotated).
- A common workaround is [a GPL or similar copyleft license](https://opensource.stackexchange.com/questions/21/whats-the-difference-between-permissive-and-copyleft-licenses/42#42), which requires the consumer to also be open source. However, that could put an undue burden on non-tech-savvy DSA consumers of this package. Even though most client-side code is technically available, is it open-source if it's not explicitly hosted on GitHub, GitLab, or similar? I wouldn't want to put that requirement on consumers.
- Another workaround is attaching [a Commons Clause](https://commonsclause.com/), which makes the software "source-available" and not "open source", and also seems to limit selling the software _itself_, when I believe our intention is to limit the context of how the software is consumed-- i.e., it should be used by non-profits, charities, and unincorporated orgs, and never by for-profit corps.
- [A non-commercial Creative Commons add-on](https://creativecommons.org/licenses/by-nc/2.0/) is another option, but it defines "commercial" activity in very broad terms that could be interpreted to include donations and "swag" that is sold to support non-profits and unincorporated orgs.

A lot of software licensing seems to be about handling of the code itself, whereas we are concerned with the context in which it is used. I can't find any licenses that handle that aspect, but perhaps I'm not searching with the right keywords since legal matters are not my wheelhouse.

**Comment by nedredmond** [comment]
I understand you're fine with MIT, but I'm exploring options!

There are two licenses I like that restrict the context that software can be used in:
https://github.com/raisely/NoHarm
https://firstdonoharm.dev/
There are others listed here: https://ethicalsource.dev/licenses/

Second, while it's not recommended by CC themselves, I may tack on a Non-Commercial 4.0 license:
https://creativecommons.org/licenses/by-nc/4.0/legalcode

Will look into it more later.
